//数据暴露
let goodsData = [{
	"id":1,
	"name":"坚果R1",
	"nametitle":"次世代旗舰手机，内藏来自未来的电脑",
	"price":"￥3,499.00",
	"imgsrc":"../../static/1.png"
  },
  {
    "id":2,
    "name":"坚果Pro2特别版",
    "nametitle":"漂亮的不像实力派",
    "price":"￥1,899.00",
    "imgsrc":"../../static/2.png"
  },
  {
    "id":3,
    "name":"坚果3",
    "nametitle":"漂亮的不像实力派",
    "price":"￥1,599.00",
    "imgsrc":"../../static/3.png"
  },
  {
    "id":4,
    "name":"坚果Pro2",
    "nametitle":"漂亮的不像实力派",
    "price":"￥2,299.00",
    "imgsrc":"../../static/4.png"
  },
  {
    "id":4,
    "name":"坚果Pro2",
    "nametitle":"漂亮的不像实力派",
    "price":"￥2,299.00",
    "imgsrc":"../../static/5.png"
  },
  {
    "id":4,
    "name":"坚果Pro2",
    "nametitle":"漂亮的不像实力派",
    "price":"￥2,299.00",
    "imgsrc":"../../static/5.png"
  },
  {
    "id":4,
    "name":"坚果Pro2",
    "nametitle":"漂亮的不像实力派",
    "price":"￥2,299.00",
    "imgsrc":"../../static/5.png"
  },
  {
    "id":4,
    "name":"坚果Pro2",
    "nametitle":"漂亮的不像实力派",
    "price":"￥2,299.00",
    "imgsrc":"../../static/5.png"
  }
  ]
export default goodsData
